class Danish {
  static Map<String, String> language = {
    "Login Here": "Skráðu þig inn hér",
    "New User": "Nýr notandi",
    "Hello, Welcome Back": "Halló, velkomin aftur",
    "Wellcome to Cucumia": "Velkominn til Cucumia",
    "Email Address": "Netfang",
    "Email must not be empty": "Tölvupóstur má ekki vera tómur",
    "Must be a valid email": "Verður að vera gilt netfang",
    "Password": "Lykilorð",
    "The password must not be empty": "Lykilorðið má ekki vera tómt",
    "The password must be at least 6 characters":
        "Lykilorðið verður að vera að minnsta kosti 6 stafir",
    "Passowrd should be alphanumeric": "Passowrd ætti að vera alfanumerískt",
    "Confirm password can not be empty":
        "Staðfestu lykilorð má ekki vera tómt",
    "Passowrd & Confirm Password must be same":
        "Passowrd & Staðfesta lykilorð verður að vera það sama",
    "Login": "Skrá inn",
    "Login Successful": "Innskráning tókst",
    "User not found": "Notandi finnst ekki",
    "Forgot Password": "Gleymt lykilorð",
    "Or Login With": "Eða Skráðu þig inn með",
    "Or Register With": "Eða Skráðu þig hjá",
    "Full Name": "Fullt nafn",
    "Name can not be empty": "Nafn má ekki vera tómt",
    "Mobile Number": "Farsímanúmer",
    "Phone can not be empty": "Síminn má ekki vera tómur",
    "Please enter a valid phone number":
        "Vinsamlegast sláðu inn gilt símanúmer",
    "Confirm Password": "Staðfesta lykilorð",
    "Register": "Skráðu þig",
    "Register Here": "Skráðu þig hér",
    "Registration Successful": "Skráning tókst",
    "Pick address": "Pick address",
    "Categories": "Flokkar",
    "Hello": "HeHallój",
    "Shops near you": "Verslanir nálægt þér",
    "Offer Magazine": "Tilboðstímarit",
    "Today's Hot Deals": "Heitt tilboð dagsins",
    "Magazines": "Tímarit",
    "Supermarket": "Stórmarkaður",
    "Bakery": "Bakarí",
    "Restaurant": "Veitingastaður",
    "View All": "Sjá allt",
    "Account Settings": "Reikningsstillingar",
    "Preferances": "óskir",
    "My Profile": "Prófílinn minn",
    "Location": "Staðsetning",
    "Location permission must be allowed":
        "Staðsetningarheimild verður að vera leyfð",
    "Change Email": "Breyta tölvupósti",
    "Change Password": "Breyta lykilorði",
    "About us": "Um okkur",
    "By Continue, Agree our ": "Með því að halda áfram, sammála okkar",
    "Terms & Conditions": "Skilmálar",
    " and Acknowledgement read our ": "og viðurkenning lestu okkar",
    "Privacy policy": "Friðhelgisstefna",
    "FAQ": "Algengar spurningar",
    "Contact Support": "Hafðu samband við þjónustudeild",
    "Log out": "Að skrá þig út",
    "Profile": "Prófíll",
    "Discount": "Afsláttur",
    "Favorites": "Uppáhalds",
    "Wellcome": "Velkominn",
    "Location Preference": "Staðsetningarval",
    "Language": "Tungumál",
    "Current Location": "Núverandi staðsetning",
    "Change Location": "Breyta staðsetningu",
    "You don't have any favorite shop": "Þú átt enga uppáhaldsbúð",
    "Favourites added": "Uppáhalds bætt við",
    "Favourites removed": "Uppáhalds fjarlægð",
    "Supermarkets near me": "Stórmarkaðir nálægt mér",
    " near me": "nálægt mér",
    "Use By": "Notaðu By",
    " to ": " til ",
    "Green Deals": "Græn tilboð",
    "Hot Deals": "Heitt tilboð",
    " from ": " frá ",
    "No deals found": "Engin tilboð fundust",
    "Timings - ": "Tímasetningar - ",
    "Call Us": "Hringdu í okkur",
    "About Us": "Um okkur",
    "Save Changes": "Vista breytingar",
    "FAQ and Support": "Algengar spurningar og stuðningur",
    "Didn't find the answer you were looking for? Contact Cucumia support!":
        "Fannstu ekki svarið sem þú varst að leita að? Hafðu samband við Cucumia stuðning!",
    "Go to our website": "Farðu á heimasíðuna okkar",
    "Chat with us": "Spjallaðu við okkur",
    "Toll Free Number": "Gjaldfrjálst númer",
    "Question": "Spurning",
    "MRP :  ": "MRP:",
    "You Save :  ": "Þú sparar :  ",
    "Inclusive of all taxes": "Að meðtöldum öllum sköttum",
    "Product's Description:": "Lýsing vöru:",
    "offer ends on": "tilboði lýkur á",
    "Message can not be empty": "Skilaboð mega ekki vera tóm",
    "Message": "Skilaboð",
    "Phone": "Sími",
    "Submit": "Sendu inn",
    "User Settings":"Notendastillingar",
    "You Save":"Þú sparar",
  };
}
